title: funny bug
author: 汤涵
 
# Header
menu:
  主页: /
  分类: /
  归档: /
  友链: /
  关于: /about

# 站点配置
site:
  # 网站logo
  logo: 
  # 显示文字
  title: 仲夏的微笑

# 标签配置
tag:
  # 标签icon，如果不配置默认使用#
  icon: fa fa-tag

links:
  github: https://github.com/tanghan-han?tab=repositories

cdn:
  jquery: 