# Header
menu:
  主页: /
  分类: /
  归档: /
  友链: /
  关于: /about

# 站点配置
site:
  # 网站logo
  logo: 


footer: 
  # 站点建立年份
  since: 2020

# 标签配置
tag:
  # 标签icon，如果不配置默认使用fa fa-tag
  icon: 

links:
  github: https://github.com/tanghan-han?tab=repositories

cdn:
  jquery: 